#!/bin/bash
GBFILE=public/javascripts/gradebook.js
ORIG_PATH="url: '/gradebook/get_data/' + grading_class_id,"
TEMP_PATH="url: '/javascripts/gradebook_201x96.json?r=' + Math.random(),"
sed -i '' "s|$ORIG_PATH|$TEMP_PATH|" $GBFILE


 
